
name: Build loong64 kernel for Debian like system

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    strategy:
      matrix:
        mmu-size: ['config-16k', 'config-4k']
    runs-on: ubuntu-latest
    name: Build loong64 kernel ${{ matrix.mmu-size }}
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout linux sources
        uses: actions/checkout@v4
        with:
          repository: AOSC-Tracking/linux
          ref: 4444b7c5ca7a8cd3e018f4c421b0737159be9ab8
          fetch-depth: 1
          submodules: recursive 
          path: 'linux'


      - name: Set up loong64 Loongnix container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/loong64/loongnix:25
          options: --privileged -v ${{ github.workspace }}:/work
          shell: bash
          run: |
            cd /work
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install sudo systemd zstd python3 libdw-dev gawk qemu-user qemu-user-binfmt debian-ports-archive-keyring devscripts equivs git xz-utils fakeroot wget curl build-essential bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev python3 dwarves bison debhelper rsync -y
            git config --global --add safe.directory /work/linux

            # Prepare env
            pushd linux

            # Build deb
            # mv -v arch/loongarch/configs/deepin_loongarch_desktop_defconfig arch/loongarch/configs/deepin_loongarch_desktop_defconfig.old
            # cp -v ../${{ matrix.mmu-size }} arch/loongarch/configs/deepin_loongarch_desktop_defconfig
            # make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- deepin_loongarch_desktop_defconfig
            cp -v ../${{ matrix.mmu-size }} .config
            export KCONFIG_CONFIG=$(realpath ./.config)            
            export lv=$(make -s kernelversion)
            export xv=""
            export rv=0
            export git=$(git rev-parse --short=7 HEAD)
            export dv=$(git show -s --date=format:'%Y%m%d' --format=%cd)
            pvcmd="cat .config | grep 'LOCALVERSION='" && export pv=$(eval $pvcmd | cut -d'"' -f2)

            make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- KDEB_PKGVERSION="$lv$pv$xv-$rv~$dv.g$git" bindeb-pkg -j$(nproc)
            popd

            # Prepare artifact
            mkdir -p assets/ && mv ./*.deb assets/

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: loong64 kernel deb for ${{ matrix.mmu-size }}
          path: assets/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
