
name: Build loong64 kernel for Debian

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  debian:
    strategy:
      matrix:
        mmu-size: ['config-16k', 'config-4k']
    runs-on: ubuntu-latest
    name: Build loong64 kernel ${{ matrix.mmu-size }}
    permissions: write-all
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 512
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Checkout linux sources
        uses: actions/checkout@v4
        with:
          repository: AOSC-Tracking/linux
          ref: 4444b7c5ca7a8cd3e018f4c421b0737159be9ab8
          fetch-depth: 1
          submodules: recursive 
          path: 'linux'


      - name: Set up loong64 Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/library/debian:trixie
          options: --privileged -v ${{ github.workspace }}:/work
          shell: bash
          run: |
            cd /work
            export DEBIAN_FRONTEND=noninteractive
            apt update
            apt install sudo systemd zstd python3 gawk qemu-user qemu-user-binfmt debian-ports-archive-keyring devscripts equivs git xz-utils fakeroot wget curl build-essential bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev python3 dwarves bison debhelper rsync -y
            git config --global --add safe.directory /work/linux

            # Prepare binfmt
            mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc
            curl -fsSL -o /usr/local/bin/systemctl-docker https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/refs/heads/master/files/docker/systemctl3.py
            chmod +x /usr/local/bin/systemctl-docker
            /usr/local/bin/systemctl-docker start systemd-binfmt.service

            # loong64
            echo "deb [signed-by=/usr/share/keyrings/debian-trixie-loong64.gpg arch=loong64] https://loong13.debian.net/debian-loong64 trixie main contrib non-free non-free-firmware" | sudo tee -a  /etc/apt/sources.list.d/debian-trixie-loong64.list
            dpkg --add-architecture loong64
            wget -O /usr/share/keyrings/debian-trixie-loong64.gpg https://loong13.debian.net/keyrings/debian-trixie-loong64.gpg
            apt update
            apt install -y gcc-loongarch64-linux-gnu libc6:loong64 libssl-dev:loong64 python3:loong64 libelf-dev:loong64

            # Prepare env
            pushd linux
            rm -rf init/build-version
            cat <<EOF >> init/build-version
            #!/bin/sh
            # SPDX-License-Identifier: GPL-2.0-only

            prev_ver=$(cat .version 2>/dev/null) &&
            ver=$(expr ${prev_ver} + 1 2>/dev/null) ||

            # Respect $prev_ver as the final build version ID.
            if [ X$prev_ver = "X" ]
            then
              ver=1
            else
              ver=$prev_ver
            fi
            echo ${ver} > .version

            echo ${ver}

            EOF
            chmod +x init/build-version

            # Build deb
            # mv -v arch/loongarch/configs/deepin_loongarch_desktop_defconfig arch/loongarch/configs/deepin_loongarch_desktop_defconfig.old
            # cp -v ../${{ matrix.mmu-size }} arch/loongarch/configs/deepin_loongarch_desktop_defconfig
            # make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- deepin_loongarch_desktop_defconfig
            cp -v ../${{ matrix.mmu-size }} .config
            export KCONFIG_CONFIG=$(realpath ./.config)            
            export lv=$(make -s kernelversion)
            export xv="-aosc1"
            export rv=0
            export git=$(git rev-parse --short=7 HEAD)
            export dv=$(git show -s --date=format:'%Y%m%d' --format=%cd)
            pvcmd="cat .config | grep 'LOCALVERSION='" && export pv=$(eval $pvcmd | cut -d'"' -f2)

            make ARCH=loongarch CROSS_COMPILE=loongarch64-linux-gnu- KDEB_PKGVERSION="$lv$pv$xv-$rv~$dv.g$git" bindeb-pkg -j$(nproc)
            popd

            # Prepare artifact
            mkdir -p assets/ && mv ./*.deb assets/

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: loong64 kernel for Debian ${{ matrix.mmu-size }}
          path: assets/*
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
